package loan.calculator.domain.entity.enum

enum class ButtonStyleEnum {
    PRIMARY_FILLED_LARGE,
    PRIMARY_FILLED_MEDIUM,
    PRIMARY_FILLED_SMALL,
    PRIMARY_OUTLINED_LARGE,
    PRIMARY_OUTLINED_MEDIUM,
    PRIMARY_OUTLINED_SMALL,
    DELETE_FILLED_LARGE,
    DELETE_FILLED_MEDIUM,
    DELETE_FILLED_SMALL,
    DELETE_OUTLINED_LARGE,
    DELETE_OUTLINED_MEDIUM,
    DELETE_OUTLINED_SMALL
}